# Generated by Django 3.1.3 on 2020-11-14 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myproject', '0001_createsuperuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('country', models.CharField(choices=[('albania', 'albania'), ('andorra', 'andorra'), ('armenia', 'armenia'), ('australia', 'australia'), ('austria', 'austria'), ('azerbaijan', 'azerbaijan'), ('belarus', 'belarus'), ('belgium', 'belgium'), ('bosnia and herzegovina', 'bosnia and herzegovina'), ('bulgaria', 'bulgaria'), ('croatia', 'croatia'), ('cyprus', 'cyprus'), ('czech republic', 'czech republic'), ('denmark', 'denmark'), ('estonia', 'estonia'), ('finland', 'finland'), ('france', 'france'), ('germany', 'germany'), ('georgia', 'georgia'), ('greece', 'greece'), ('hungary', 'hungary'), ('iceland', 'iceland'), ('ireland', 'ireland'), ('israel', 'israel'), ('italy', 'italy'), ('latvia', 'latvia'), ('lithuania', 'lithuania'), ('luxembourg', 'luxembourg'), ('macedonia', 'macedonia'), ('malta', 'malta'), ('moldova', 'moldova'), ('monaco', 'monaco'), ('montenegro', 'montenegro'), ('morocco', 'morocco'), ('netherlands', 'netherlands'), ('norway', 'norway'), ('poland', 'poland'), ('portugal', 'portugal'), ('romania', 'romania'), ('russia', 'russia'), ('san marino', 'san marino'), ('serbia', 'serbia'), ('slovenia', 'slovenia'), ('slovakia', 'slovakia'), ('spain', 'spain'), ('sweden', 'sweden'), ('switzerland', 'switzerland'), ('turkey', 'turkey'), ('ukraine', 'ukraine'), ('united kingdom', 'united kingdom'), ('yugoslavia', 'yugoslavia')], max_length=256)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter', models.CharField(max_length=64)),
                ('score', models.IntegerField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.entry')),
            ],
        ),
    ]
