# Generated by Django 3.1.3 on 2020-11-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='code',
            field=models.CharField(default='xxxx', max_length=256),
        ),
        migrations.AlterField(
            model_name='entry',
            name='artist',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
