# Generated by Django 3.1.3 on 2020-11-18 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0005_create_nf_people_choice_entries_1_s1'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='edition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myproject.edition'),
        ),
    ]
