# Generated by Django 3.1.3 on 2020-11-14 18:52

from django.db import migrations
from django.db.migrations import RunPython

from myproject.inputs.pc_nf_2 import pc_nf_1_semi_2


def create_entries(apps, schema_editor):
    entries = []
    Entry = apps.get_model("myproject", "Entry")
    Edition = apps.get_model("myproject", "Edition")
    edition, _ = Edition.objects.get_or_create(name="People's Choice: Robbed Semi 2", year=0)
    for entry in pc_nf_1_semi_2:
        split = entry.split("\t")
        year = split[0]
        country = split[1]
        artist = split[2]
        song = split[3]
        code = split[4]
        e = Entry(artist=artist, title=song, code=code, year=year,country=country)
        entries.append(e)
    Entry.objects.bulk_create(entries)


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0007_apply_first_edition'),
    ]

    operations = [RunPython(create_entries)]
