# Generated by Django 3.1.3 on 2020-11-14 18:52

from django.db import migrations
from django.db.migrations import RunPython

from myproject.inputs.injusticia_2_sf1 import injusticia_2_entries_2, injusticia_2_entries_1
from myproject.inputs.nesbea import nesbeas2


def create_entries_1(apps, schema_editor):
    entries = []
    Entry = apps.get_model("myproject", "Entry")
    Edition = apps.get_model("myproject", "Edition")
    edition, _ = Edition.objects.get_or_create(name="Non ESC songs Semi 2", year=1)
    for entry in nesbeas2:
        year = 0
        country = "nvm"
        artist = "nvm"
        song = "nvm"
        code = entry
        e = Entry(artist=artist, title=song, code=code, year=year,country=country)
        entries.append(e)
    Entry.objects.bulk_create(entries)

class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0011_create_nesbea_S1_entries'),
    ]

    operations = [RunPython(create_entries_1)]
