# Generated by Django 3.1.3 on 2020-11-14 18:52

from django.db import migrations
from django.db.migrations import RunPython

from myproject.inputs.injusticia_2_sf1 import injusticia_2_entries_2, injusticia_2_entries_1
from myproject.inputs.nesbea import nesbeas2

list = [
"austria2021",
"slovenia2021",
"iceland2001",
"malta2005",
"switzerland2004",
"croatia2011",
"sweden1988",
"azerbaijan2008",
"yugoslavia1981",
"bosnia2006",
"belgium1987",
"denmark2016",
"iceland2000",
"spain2003",
"ukraine2014",
"croatia2021",
"israel2012",
"belarus2015",
"georgia2015",
"malta2015",
"sweden2013",
"macedonia2020",
"hungary2014",
"cyprus2020",]

def create_entries_1(apps, schema_editor):
    entries = []
    Entry = apps.get_model("myproject", "Entry")
    Edition = apps.get_model("myproject", "Edition")
    edition, _ = Edition.objects.get_or_create(name="Duels1", year=1)
    for entry in list:
        year = 0
        country = "nvm"
        artist = "nvm"
        song = "nvm"
        code = entry
        e = Entry(artist=artist, title=song, code=code, year=year,country=country)
        entries.append(e)
    Entry.objects.bulk_create(entries)

class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0012_create_nesbea_S2_entries'),
    ]

    operations = [RunPython(create_entries_1)]
