# Generated by Django 3.1.3 on 2020-11-14 18:52

from django.db import migrations
from django.db.migrations import RunPython

from myproject.inputs.injusticia_2_sf1 import injusticia_2_entries_2, injusticia_2_entries_1
from myproject.inputs.nesbea import nesbeas2

list = ['sweden2009',
'ireland1996',
'bosniaandherzegovina2016',
'sweden1998',
'iceland2004',
'montenegro2019',
'ireland2005',
'lithuania2009',
'armenia2006',
'ireland2001',
'greece2003',
'russia2006',
'malta2010',
'greece2018',
'belarus2017',
'ireland2020',
'lithiania2014',
'norway2020',
'iceland2008',
'sweden2010',
'ukraine2003',
'belarus2008',
'georgia2010',
'netherlands2009']

def create_entries_1(apps, schema_editor):
    entries = []
    Entry = apps.get_model("myproject", "Entry")
    Edition = apps.get_model("myproject", "Edition")
    edition, _ = Edition.objects.get_or_create(name="Duels2", year=1)
    for entry in list:
        year = 0
        country = "nvm"
        artist = "nvm"
        song = "nvm"
        code = entry
        e = Entry(artist=artist, title=song, code=code, year=year,country=country)
        entries.append(e)
    Entry.objects.bulk_create(entries)

class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0013_duels1'),
    ]

    operations = [RunPython(create_entries_1)]
