# Generated by Django 3.1.3 on 2020-11-14 18:52

from django.db import migrations
from django.db.migrations import RunPython

from myproject.inputs.injusticia_2_sf1 import injusticia_2_entries_2, injusticia_2_entries_1
from myproject.inputs.nesbea import nesbeas2

list = ["norway2021witchwoods",
"italy2021unmilionidicosadadirti",
"sweden2021littletot",
"france2021magique",
"norway2021nordlyset",
"estonia2021tartu",
"sweden2021onetouch",
"portugal2021namaisprofundasaudade",
"finland2021iloveyou",
"albania2021pendese",
"croatia2021mazamisli",
"portugal2021volteface",
"france2021bahnon",
"sweden2021themissingpiece",
"norway2021monument",
"italy2021chiamamipernome",
"bulgaria2021thefuneralsong",
"sweden2021renaramadingdong",]

def create_entries_1(apps, schema_editor):
    entries = []
    Entry = apps.get_model("myproject", "Entry")
    Edition = apps.get_model("myproject", "Edition")
    edition, _ = Edition.objects.get_or_create(name="Injusticia21-semi1", year=1)
    for entry in list:
        year = 0
        country = "nvm"
        artist = "nvm"
        song = "nvm"
        code = entry
        e = Entry(artist=artist, title=song, code=code, year=year,country=country)
        entries.append(e)
    Entry.objects.bulk_create(entries)

class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0014_duels2'),
    ]

    operations = [RunPython(create_entries_1)]
