# Generated by Django 3.1.3 on 2020-11-14 18:52

from django.db import migrations
from django.db.migrations import RunPython

from myproject.inputs.injusticia_2_sf1 import injusticia_2_entries_2, injusticia_2_entries_1
from myproject.inputs.nesbea import nesbeas2

list = ["sweden2021stillyoung",
"albania2021vashezo",
"france2021amourfou",
"norway2021ican'tescape",
"sweden2021bailabaila",
"finland2021kellemäsoitan",
"italy2021potevifaredipiù",
"france2021onamangélesoleil",
"albania2021nesevdes",
"lithuania2021home",
"israel2021uelala",
"sweden2021behöverintedigidag",
"norway2021letloose",
"france2021pourvuqu'onm'aime",
"belarus2021braids",
"sweden2021everyminute",
"italy2021voce",
"estonia2021magusmelanhoolia",
"france2021maeva",]

def create_entries_1(apps, schema_editor):
    entries = []
    Entry = apps.get_model("myproject", "Entry")
    Edition = apps.get_model("myproject", "Edition")
    edition, _ = Edition.objects.get_or_create(name="Injusticia21-semi2", year=1)
    for entry in list:
        year = 0
        country = "nvm"
        artist = "nvm"
        song = "nvm"
        code = entry
        e = Entry(artist=artist, title=song, code=code, year=year,country=country)
        entries.append(e)
    Entry.objects.bulk_create(entries)

class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0015_injustcia21_1'),
    ]

    operations = [RunPython(create_entries_1)]
