# Generated by Django 3.1.3 on 2020-11-14 18:52

from django.db import migrations
from django.db.migrations import RunPython

from myproject.inputs.injusticia_2_sf1 import injusticia_2_entries_2, injusticia_2_entries_1
from myproject.inputs.nesbea import nesbeas2

list = ["lithuania",
"slovenia",
"russia",
"sweden",
"australia",
"macedonia",
"ireland",
"cyprus",
"norway",
"croatia",
"belgium",
"israel",
"romania",
"azerbaijan",
"ukraine",
"malta",]

def create_entries_1(apps, schema_editor):
    entries = []
    Entry = apps.get_model("myproject", "Entry")
    Edition = apps.get_model("myproject", "Edition")
    edition, _ = Edition.objects.get_or_create(name="2021-semi1", year=1)
    for entry in list:
        year = 0
        country = "nvm"
        artist = "nvm"
        song = "nvm"
        code = entry
        e = Entry(artist=artist, title=song, code=code, year=year,country=country)
        entries.append(e)
    Entry.objects.bulk_create(entries)

class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0016_injustcia21_2'),
    ]

    operations = [RunPython(create_entries_1)]
