COUNTRY_LIST=[
    ("albania", "albania"),
    ("andorra", "andorra"),
    ("armenia", "armenia"),
    ("australia", "australia"),
    ("austria", "austria"),
    ("azerbaijan", "azerbaijan"),
    ("belarus", "belarus"),
    ("belgium", "belgium"),
    ("bosnia and herzegovina", "bosnia and herzegovina"),
    ("bulgaria", "bulgaria"),
    ("croatia", "croatia"),
    ("cyprus", "cyprus"),
    ("czech republic", "czech republic"),
    ("denmark", "denmark"),
    ("estonia", "estonia"),
    ("finland", "finland"),
    ("france", "france"),
    ("germany", "germany"),
    ("georgia", "georgia"),
    ("greece", "greece"),
    ("hungary", "hungary"),
    ("iceland", "iceland"),
    ("ireland", "ireland"),
    ("israel", "israel"),
    ("italy", "italy"),
    ("latvia", "latvia"),
    ("lithuania", "lithuania"),
    ("luxembourg", "luxembourg"),
    ("macedonia", "macedonia"),
    ("malta", "malta"),
    ("moldova", "moldova"),
    ("monaco", "monaco"),
    ("montenegro", "montenegro"),
    ("morocco", "morocco"),
    ("netherlands", "netherlands"),
    ("norway", "norway"),
    ("poland", "poland"),
    ("portugal", "portugal"),
    ("romania", "romania"),
    ("russia", "russia"),
    ("san marino", "san marino"),
    ("serbia", "serbia"),
    ("slovenia", "slovenia"),
    ("slovakia", "slovakia"),
    ("spain", "spain"),
    ("sweden", "sweden"),
    ("switzerland", "switzerland"),
    ("turkey", "turkey"),
    ("ukraine", "ukraine"),
    ("united kingdom", "united kingdom"),
    ("yugoslavia", "yugoslavia"),
]